### PR TITLE
Env configuration

### PR DESCRIPTION
**Pull request by jmbarne3**
Enhancements:
* Removed the `settings_local.templ.py` file. The `settings_local.py` file will no longer be necessary for configuration the application.
* Added the `.env.templ` file with all the available configuration items listed and commented out. As all of the settings now have default defined within the `settings.py` file, this file is not necessary, but can be used to overwrite the defaults.
* Updated the `settings.py` file to (1) search for a `.env` file and then use any settings defined within that `.env` file first. If no setting is provided, it will fallback to the provided default. In some cases, I am checking the existence of the setting before defining the setting, because Django uses whether the setting exists as an indication of whether certain features should be used or not - specifically when dealing with static files.

### CODE REVIEW

**Comment by jmbarne3** [comment]
Resolves #76

**Comment by ucfchandra** [comment]
@jmbarne3 please review to ensure that my changes are aligned

**Review by ucfchandra — COMMENTED** [review]
Changed ALLOWED_HOSTS and STATIC_ROOT so container builds. Should these always be commented out by default?

**Review by Ramin-Farhadi — APPROVED** [review]

**Comment by jmbarne3** [comment]
@ucfchandra The purpose of the branch was to get settings loaded in via an `.env` file when developing locally. As a matter of principle, I should be able to run this project without starting it in a container, which is possible without setting any of the specific settings in the `.env` file. This was intentional. By default, the application will run when you run `python manage.py runserver` without having to create the `.env` file.

If a developer wants to utilize the containerfile and develop using that method, they will need to follow a set of instructions to prepare their environment for development. It sounds like one of these steps is going to be creating an `.env` file and setting the `ALLOWED_HOSTS` and `STATIC_ROOT` settings. Figuring out what steps are necessary for the image to run is a task already assigned to you in #75, and therefore was not the purpose of this set of changes.

Additionally, as a matter of courtesy, please do not commit directly onto someone else's branch without asking them. You're welcome to suggest a change during a review and we can discuss the change here, but allow the developer who posted the pull request to make the change or to argue against it.

**Pull request merged**
